opentelemetry-collector:
  mode: deployment

  config:
    extensions:
      oidc:
        issuer_url: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_XXXXXX # Replace with your Cognito User Pool ID
        audience: "api://default"
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
      memory_ballast: {}
      sigv4auth:
        region: us-east-2
        assume_role:
          # IAM role in your AWS account which grants permission to write metrics to AMP
          arn: "arn:aws:iam::XXXXX:role/amp-ingest-role" # Replace with your AMP Ingest Role ARN
          sts_region: "us-east-2"

    exporters:
      prometheusremotewrite:
        auth:
          authenticator: sigv4auth
        endpoint: https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-xxxxxx/api/v1/remote_write # Replace with your AMP Remote Write URL

    receivers:
      jaeger: {}
      otlp:
        protocols:
          http:
            auth:
              authenticator: oidc
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 10s
              static_configs:
                - targets: []

    processors:
      attributes/shipper:
        actions:
          - key: etip_source_cluster
            value: custom-onprem-otel-gateway # Replace with your source cluster name
            action: upsert

    service:
      extensions:
        - health_check
        - memory_ballast
        - oidc
        - sigv4auth

      pipelines:
        metrics:
          exporters:
            - prometheusremotewrite

      telemetry:
        metrics:
          address: ":8888"

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    ingressClassName: nginx
    hosts:
      - host: custom-otel-pushgateway.example.com # Replace with your custom domain
        paths:
          - path: /
            pathType: Prefix
            port: 4318
    tls:
      - secretName: otel-gateway-tls
        hosts:
          - custom-otel-pushgateway.example.com # Replace with your custom domain

  serviceAccount:
    annotations:
      # IAM role in EKS cluster's AWS account that allows sigv4 extension to assume role in your AWS account
      eks.amazonaws.com/role-arn: "arn:aws:iam::XXXXX:role/amp-ingest-role" # Replace with your AMP Ingest Role ARN

  ports:
    metrics:
      enabled: true

  serviceMonitor:
    enabled: true
    metricsEndpoints:
      - port: metrics
        interval: 15s
    extraLabels:
      prometheus: default